name: sync-action

on:
  push:
    branches:
    - master
    - develop
    - qa
    - release
    - code_quality
  delete:
    branches:
    - master
    - develop
    - qa
    - release
    - code_quality
    branches-ignore:
    - 'test1'

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        target-url: https://gitlab.com/kirantejaa74/aem-test-remote.git
        # Such as wangchucheng
        target-username: kirantejaa74
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
        target-token: s1zhMiv7__GsMn_gGUyc
