name: sync-action

on:
  push:
    branches:
    - master
    - develop
    - qa
    - release
    - code_quality
    - main
    - test
  delete:
    branches:
    - master
    - develop
    - qa
    - release
    - code_quality
    - main
    - test

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://kirantejaa74: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@github.com/kirantejaa74/aem-test.git"
          source_branch: "${GITHUB_REF##*/}"
          destination_repo: "https://kirantejaa74:otMwuPvJyTJkbN3ys1Hz@gitlab.com/kirantejaa74/aem-test-remote.git"
          destination_branch: "${GITHUB_REF##*/}"
