name: sync-action

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://kirantejaa74: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@github.com/kirantejaa74/aem-test.git"
          source_branch: "main"
          destination_repo: "https://kirantejaa74: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@github.com/kirantejaa74/aem-test-1.git"
          destination_branch: "main"
