name: sync-action

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "kirantejaa74/aem-test"
          source_branch: "main"
          destination_repo: "kiranteja-ta/aem-test-remote"
          destination_branch: "main"
