name: sync-action

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://kirantejaa74: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@github.com/kirantejaa74/aem-test.git"
          source_branch: "main"
          destination_repo: "https://rajeev-duggal-tadigital-com:auuso2hscjeoa4d3lp2tvepsvahi6m7cfdt2gfsl4v4hyjnyed6a@git.cloudmanager.adobe.com/h2oai/H2O-Website-Github/"
          destination_branch: "main"
